# TODO: hard-coded values
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-proj
  labels:
    app: flexo
    type: api
spec:
  replicas: 3
  selector:     # how will the deployment find its pods ?
    matchLabels:        # should satisfy the labels provided by pods
      app: flexo
      type: api
  template:
    metadata:
      name: flexo-engine
      labels:   # pods labels. creates selectors for pods
        app: flexo
        type: api
    spec:
      containers:       # containers running on this pod (only one here)
      - name: flexo
        # TODO: THIS SHOULD BE PRIVATE!
        image: 421352775051.dkr.ecr.ap-northeast-2.amazonaws.com/seccdc/flexo:latest
        # TODO: start here
        env:
          - name: DBADDR
            value: postgres:5432   # TODO: will port num work ?
          - name: DBUSER
            value: flexo
          - name: DBPASS
            value: flexo
          - name: DBNAME
            value: flexo
          - name: DBSSL
            value: disable
          - name: SECRET
            value: shared_secret

        ports:        # TODO: does this expose ports ?
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: flexo-svc
  labels:
    app: flexo
spec:
  type: NodePort
  ports:
   - port: 8080
  selector:
   app: flexo
   type: api
